# Basic dependabot.yml file
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every month
    schedule:
      interval: "monthly"
    # Usually only bump versions in package-lock.json, but update package.json for major version updates
    versioning-strategy: "increase-if-necessary"
    # Update all dependencies in a single PR
    groups:
      # ESLint usually requires updating together for major updates
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      # Other updates should be okay all at once
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@mdn/*"
          - "@webref/*"
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
